message("Begin internal test")
start = Sys.time()
source("/home/SingleCellPlus/qc.R")
rm(list=ls())
gc()
source("/home/SingleCellPlus/scMerge.R")
rm(list=ls())
gc()
source("/home/SingleCellPlus/downstream.R")
rm(list=ls())
gc()
end = Sys.time()

message("The test completed in ", round(end - start, 2), " mins! You are good to go!")
